### ISSUE TITLE
Save new contact error: No Accounts!

### ISSUE THREAD

**Issue by MrDigii** [firescript/nativescript-contacts#15] opened 2016-07-18 09:43 UTC
Hi,
I working on a nativescript app for android and iOS. I want implement a feature to add contacts to the device. Therefore I tested this plugin. I used exactly the code from npm plugin website for **Save a new contact** to do this. But on emulator and also on android device it stops with this error message:

Error: No Accounts! .../app/tns_modules/nativescript-contacts/contact-model.js, line: 200, column: 12

**Comment by MrDigii** [comment] 2016-07-21 07:45
I think it is solved. I try to use the app on a android phone **with SIM Card** inside and it worked. On Iphone the plugin added contact also without SIM. But I would be very pleased to get a success or error response if a contact is saved. Is this possible?

**Comment by rajasekarsp** [comment] 2017-07-07 13:56
This issue is poping up for me. Any Fixes?

**Comment by jzgoda** [comment] 2019-04-18 15:11
I'm closing this because it's been about 2 years without activity.

If it continues to throw an error, please include a reproducible example of the error.

**Closed by jzgoda** 2019-04-18 15:11 UTC
