### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by stuartandrews93** [firescript/nativescript-contacts#19] opened 2017-02-09 09:58 UTC
I've been trying to get all the contacts from my phone's contact list with the getAllContacts() function. I have been encountering an error I can't seem to fix:

Error: Error
java.io.FileNotFoundException: content://com.android.contacts/contacts/1/photo

I can access the native list just fine, and I can pull single contacts just fine, but I'd prefer the functionality of being able to pull the entire list.

Any suggestions?

**Comment by jzgoda** [comment] 2019-04-18 15:09
I'm closing this because it's over 2 years old without activity.

If it continues to throw an error, please include a reproducible example of the error.

**Closed by jzgoda** 2019-04-18 15:09 UTC
