### ISSUE TITLE
Plugin conflits when using nativescript-admob and nativescript-telerik-ui

### ISSUE THREAD

**Issue by calebeaires** [firescript/nativescript-contacts#11] opened 2016-04-09 14:27 UTC
nativescript-contacts plugin alone with nativescript-admob or it alone with nativescript-telerik-ui pass on build, but when I use it with both, the build get this error:

```
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class android.support.v7.appcompat.R$drawable conflict: /Users/macbook/Downloads/agua/platforms/android/build/intermediates/classes/admobNativescript-telerik-ui/debug and /Users/macbook/Downloads/agua/platforms/android/build/intermediates/classes/admobNativescript-contactsNativescript-telerik-ui/debug
    at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
    at com.telerik.metadata.Builder.build(Builder.java:41)
    at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED
```

**Comment by PeterStaev** [comment] 2016-04-09 14:49
The contacts plugin does not use any resources nor uses the appcompat support. Have you tried building the app with admob and telerik-ui? I suspect the problem is the two have some same named resources.

**Comment by calebeaires** [comment] 2016-04-09 15:54
I have tried it right now. When using just nativescript-admob and nativescript-telerik-ui on a blank nativescript app, it works. But, using the tree plugins together, it break.

**Comment by jzgoda** [comment] 2019-04-18 15:15
I'm closing this because it's been over 3 years without activity.

If it continues to be an issue, please include a reproducible example of the error.

**Closed by jzgoda** 2019-04-18 15:15 UTC
